spring:
  application:
    name: TestYouAi

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/teste10;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  ai:
    openai:
      api-key:
      chat:
        model: gpt-4-turbo
