spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testyouai_db
    username: testyouai_user
    password: testyouai_pass
    driver-class-name: org.postgresql.Driver
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

